### ISSUE TITLE
Case-sensitive tag names

### ISSUE THREAD

**Issue by ArvedEh** [devcordde/DevcordBot#105]
Tag names are case-sensitive.
Example:
`st lernjava` does not give the same result as `st Lernjava`

This can be quite annoying at times, although the bot already tells you the right lowercase name.
My suggestion is to just make the comparison case-insensitive.

**Comment by DRSchlaubi** [comment]
TBH it did not occur to me once since even my spell checker on my phone only capitalizes the first word in a message. But should be an easy fix (if you are able to understand the mess in TagCommand.kt)
