### ISSUE TITLE
Raw tags can exceed char limit

### ISSUE THREAD

**Issue by DRSchlaubi** [devcordde/DevcordBot#119]
@JohnnyJayJay WHY TEH HECK IS YOUR lernjava TAG SO LONG

Log: https://haste.devcord.xyz/yecemacoro

Credit: @Veteranfighter

**Comment by Veteranfighter** [comment]
![lul](https://user-images.githubusercontent.com/63098858/89741292-4c642a00-da90-11ea-9a18-0060ba1a4178.png)
