### ISSUE TITLE
Automod issues

### ISSUE THREAD

**Issue by daspositioned** [devcordde/DevcordBot#147]
https://discord.com/channels/486161636105650176/486919573229010944/813529976816795658

**Comment by JahisanaMalimimbra** [comment]
Unban thx

**Comment by daspositioned** [comment]
https://discord.com/channels/486161636105650176/486919187038470155/819665061513134080

**Comment by DRSchlaubi** [comment]
I wrote a new parser for stack traces which should not be as sensitive for false positives as the old one.
