### ISSUE TITLE
Devmarkt Feature

### ISSUE THREAD

**Issue by daspositioned** [devcordde/DevcordBot#16]
Eine Verwaltung des Devmarkts mit dem Bot ermöglichen, damit die Moderation von diesem vereinfacht wird

**Comment by jkoenig134** [comment]
Da im Devmarkt immer nur der Gleiche Müll geschrieben wird ([Schloool, 19.05.2020](https://discordapp.com/channels/486161636105650176/551797097045688320/712294040351145994)) wird dieser nicht mehr moderiert.
Das feature ist damit hinfällig.

**Comment by jkoenig134** [comment]
Tills devmarkt wird wieder eingesetzt
