### ISSUE TITLE
Some descriptions of slash commands are wrong

### ISSUE THREAD

**Issue by Taucher2003** [devcordde/DevcordBot#174]
As mentioned in the title, there are multiple commands with a wrong description.

![Screenshot_20210507-080319_Discord](https://user-images.githubusercontent.com/39954661/117404725-bd931980-af0a-11eb-9720-bc209074f8da.jpg)

I don't know if you can edit descriptions for subcommands, but these descriptions can be misleading

**Comment by DRSchlaubi** [comment]
Looks like subcommands inherit their descriptions from the parent command the commit above should fix it
