### ISSUE TITLE
Survey feature

### ISSUE THREAD

**Issue by Paul2708** [devcordde/DevcordBot#23]
Creating a survey with a question and different answers.
Users can vote by reaction.

**Comment by DRSchlaubi** [comment]
It already took ages to make https://top.gg/bot/569936566965764126 not doing that again

**Comment by jkoenig134** [comment]
We could use strawpoll´s REST api @DRSchlaubi

**Comment by DRSchlaubi** [comment]
I mean we could also use votebot

**Comment by jkoenig134** [comment]
So we close it?

**Comment by DRSchlaubi** [comment]
yep
