### ISSUE TITLE
Eval funciton

### ISSUE THREAD

**Issue by Paul2708** [devcordde/DevcordBot#24]
Run small code snippets.

**Comment by DRSchlaubi** [comment]
jdoodle?

**Comment by Paul2708** [comment]
I'm not very familiar with online compiler. There is also [https://repl.it/](https://repl.it/), but idk. 
So I think JDoodle should be fine. Otherwise the feature can be extended in the future.

**Comment by DRSchlaubi** [comment]
Repl.it does provide such a feature?

**Comment by jkoenig134** [comment]
@Paul2708 & @DRSchlaubi repl.it doesn´t provide an api to execute code. I will implement it using jdoodle if there is no better idea.

**Comment by DRSchlaubi** [comment]
At least we know JDoodle works
