### ISSUE TITLE
Eine Topliste für die User mit den meisten Nachrichten

### ISSUE THREAD

**Issue by TheZexquex** [devcordde/DevcordBot#30]
Ich fände eine Toplist interessant, die, ähnlich wie **rank top**, anzeigt welcher User die meisten Nachrichten geschrieben hat

**Comment by jkoenig134** [comment]
@TheZexquex So einen Command gibt es doch schon..? Soll `rank top` die Anzahl der geschriebenen Nachrichten noch mit anzeigen?

**Comment by TheZexquex** [comment]
Das wäre eine gute Idee. Ich fände es einfach an sich interessant, da es das Rang System ja noch nicht so lange gibt wie Nachrichten gesendet wurden.

**Comment by DRSchlaubi** [comment]
Gibt es überhaupt die Möglichkeit Nachrichten zu zählen? Die discord suche kann das aber Bots?

**Comment by jkoenig134** [comment]
@DRSchlaubi guter Punkt. Ich dachte ich hätte das mal bei einem Bot gesehen.

**Comment by DRSchlaubi** [comment]
Du kannst die history von jedem channel durchgehen und nach user filtern aber das ist dumm, weil:
- Du wirst safe geratelimmited weil du es zu oft machen musst
- Die history ist auf 2 Wochen oder so begrenzt
- Zu viele Request, wird performance vom bot stark beinflussen

**Comment by jkoenig134** [comment]
Alles klar.
