### ISSUE TITLE
Tag name blacklist

### ISSUE THREAD

**Issue by lus** [devcordde/DevcordBot#42]
Aktuell kann man Tags mit Namen wie `create test` erstellen, welche dann nicht mehr aufrufbar sind.

**Comment by DRSchlaubi** [comment]
Eigentlich sollte das ganze ja hiervon geprüft werden https://github.com/devcordde/DevcordBot/blob/2978cf9a7e7d0ce653041a675f001daafa697ca0/src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt#L413-L424

https://github.com/devcordde/DevcordBot/blob/2978cf9a7e7d0ce653041a675f001daafa697ca0/src/main/kotlin/com/github/seliba/devcordbot/commands/general/TagCommand.kt#L63

**Comment by lus** [comment]
Da der Name ja aus mehreren Wörtern bestehen kann und der Code den kompletten Namen überprüft, kann man auch teile von reservierten Namen nutzen.

**Comment by DRSchlaubi** [comment]
Jap hab ich inzwischen auch gemerkt
