### ISSUE TITLE
Discussion: Make levels great again

### ISSUE THREAD

**Issue by DRSchlaubi** [devcordde/DevcordBot#52]
- Make levels based on message length, something like `HIII!` is not worth any XP
- Ignore messages that only/for the most part consist of code blocks completely
- Ignore messages that only link to hastebin
- Improve level formula -  IDK Math but the current formula needs to be improved
- Make XP random - currently every message = 5 XP
- when you get a higher level it's harder to level up but you also get more XP because it looks like your good contributor cc @amejonah1200

**Comment by jkoenig134** [comment]
This will be discussed on another platform (via #rat-chat). Your ideas have been and will be considered.
