### ISSUE TITLE
caseSensitive bei subCommands von tag

### ISSUE THREAD

**Issue by Randoooom** [devcordde/DevcordBot#57]
Die subCommands von `tag`  müssen derzeit immer **klein** geschrieben werden. Es wäre sehr praktisch, vorallem für die Handy-Nutzer, wenn die Groß- und Kleinschreibung dort einfach ignoriert werden würde.

LG Random

PS: bei den Namen eines tags wäre dies auch gut

**Comment by DRSchlaubi** [comment]
Bei votebot hatte ich das glaube ich mal gefixed hier aber nicht, irgendwie dumm 2x die gleiche codebase zu nutzen
