### ISSUE TITLE
moderation

### ISSUE THREAD

**Issue by jkoenig134** [devcordde/DevcordBot#81]
Der bot soll die Moderation von Dyno ersetzen.

Vorläufige Features die wir benötigen:
- ban
- tempban
- mute
- block
- (userinfo)
- modlog

**Comment by DRSchlaubi** [comment]
Actually is this still up to date?

**Comment by jkoenig134** [comment]
Nope

**Comment by daspositioned** [comment]
I'll work on it soon

**Comment by DRSchlaubi** [comment]
We should probably reopen it?
