### ISSUE TITLE
'sch' prefix

### ISSUE THREAD

**Issue by lus** [devcordde/DevcordBot#91]
I need it.

**Comment by DRSchlaubi** [comment]
why?

**Comment by jkoenig134** [comment]
Alias chrank for rank would be better @Lukaesebrot

**Comment by DRSchlaubi** [comment]
When he gets his prefix I want to get OCR for auto-help

**Comment by jkoenig134** [comment]
That prefix wont come.

**Comment by DRSchlaubi** [comment]
I want it anyways

**Comment by lus** [comment]
`chrank` alias is okay too.

**Comment by jkoenig134** [comment]
Can't explain one or the other to anyone @Lukaesebrot

**Comment by lus** [comment]
so it's denied?

**Comment by jkoenig134** [comment]
It is - even it was a **fabulous** idea. I am sorry.

**Comment by lus** [comment]
you cannot do that to me :c. I will explain it if needed

**Comment by jkoenig134** [comment]
added with #95 as `sudo cooler hipster rank`
