### ISSUE TITLE
Add OCR to autohelp

### ISSUE THREAD

**Issue by DRSchlaubi** [devcordde/DevcordBot#98]
There are some people who think it is clever to sent errors as screenshots because they don't know how to use haste

**Comment by jkoenig134** [comment]
OCR was already considered as not coming to DevcordBot

**Comment by DRSchlaubi** [comment]
I always knew I cannot trust you: https://discord.com/channels/486161636105650176/551797097045688320/723917657291751475
https://rice.by.devs-from.asia/msedge_HU099TCNcB.png

**Comment by jkoenig134** [comment]
10 years ago
